name: frps-arm64v8
on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: frps/arm64v8
          platforms: linux/arm64
          push: true
          tags: |
            snowdreamtecharm64v8/frps:latest
            snowdreamtecharm64v8/frps:0.45.0
            ghcr.io/snowdreamtech/frps:arm64v8-latest
            ghcr.io/snowdreamtech/frps:arm64v8-0.45.0